server:
  port: 8887
spring:
  application:
    name: consumer
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/

#设置超时时间 openFeign 默认支持
#ribbon:
#  ReadTimeout: 5000
#  ConnectTimeout: 5000