server:
  port: 8888
spring:
  application:
    name: order-one

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000



